// src/components/TvPresentationMode.vue
<template>
  <div class="fixed inset-0 z-50 bg-[#070d19] text-slate-100 flex flex-col justify-between p-6 lg:p-10 select-none animate-fade-in">
    
    <!-- TV Header -->
    <div class="flex items-center justify-between border-b border-slate-800 pb-4">
      <div class="flex items-center gap-3">
        <div class="w-12 h-12 rounded-2xl bg-gradient-to-tr from-blue-600 to-amber-500 p-0.5 shadow-xl">
          <div class="w-full h-full bg-slate-950 rounded-[14px] flex items-center justify-center">
            <GraduationCap class="w-6 h-6 text-amber-400" />
          </div>
        </div>
        <div>
          <h1 class="text-xl lg:text-2xl font-black uppercase tracking-wider bg-gradient-to-r from-amber-200 via-amber-400 to-amber-500 bg-clip-text text-transparent">
            PAINEL EXECUTIVO DE INTELIGÊNCIA EDUCACIONAL
          </h1>
          <p class="text-xs lg:text-sm text-slate-400 font-semibold">
            MUNICÍPIO MODELO • MODA TV TRANSMISSÃO AO VIVO
          </p>
        </div>
      </div>

      <div class="flex items-center gap-4">
        <div class="flex items-center gap-2 bg-slate-900 border border-slate-800 px-3 py-1.5 rounded-xl text-xs font-mono text-emerald-400">
          <span class="w-2 h-2 rounded-full bg-emerald-400 animate-ping"></span>
          <span>SINAL AO VIVO • {{ currentTime }}</span>
        </div>

        <button
          @click="isTvMode = false"
          class="p-2.5 bg-slate-800 hover:bg-slate-700 text-slate-300 hover:text-white rounded-xl border border-slate-700 transition-colors"
          title="Sair do Modo TV"
        >
          <X class="w-6 h-6" />
        </button>
      </div>
    </div>

    <!-- TV Main Slide Content -->
    <div class="my-auto py-6">
      
      <!-- Slide 0: General Score & Main Goal -->
      <div v-if="activeSlide === 0" class="space-y-8 max-w-5xl mx-auto text-center">
        <span class="px-4 py-1.5 rounded-full bg-amber-500/10 text-amber-400 text-sm font-bold uppercase tracking-widest border border-amber-500/20">
          Índice Geral de Desempenho Educacional
        </span>

        <div class="flex items-center justify-center gap-6 my-6">
          <div class="text-7xl lg:text-9xl font-black text-white tracking-tight">
            72.4 <span class="text-3xl text-slate-500 font-normal">/ 100</span>
          </div>
        </div>

        <div v-if="mainGoal" class="bg-slate-900/90 border border-slate-800 p-6 rounded-2xl max-w-3xl mx-auto shadow-2xl">
          <div class="text-xs uppercase font-extrabold text-amber-400 tracking-wider mb-2">
            META MUNICIPAL A PERSEGUIR ATÉ {{ mainGoal.targetYear }}
          </div>
          <div class="text-2xl font-black text-slate-100">
            Atingir {{ mainGoal.targetValue }} {{ mainGoal.targetUnit }}
          </div>
          <div class="w-full bg-slate-950 rounded-full h-3 my-4 border border-slate-800">
            <div
              class="h-full bg-gradient-to-r from-blue-500 to-amber-400 rounded-full"
              :style="{ width: `${(mainGoal.currentValue / mainGoal.targetValue) * 100}%` }"
            ></div>
          </div>
          <p class="text-xs text-slate-400 italic">"{{ mainGoal.motto }}" — {{ mainGoal.description }}</p>
        </div>
      </div>

      <!-- Slide 1: Primary Indicators -->
      <div v-else-if="activeSlide === 1" class="max-w-6xl mx-auto space-y-6">
        <div class="text-center mb-6">
          <h2 class="text-xl lg:text-2xl font-black uppercase text-amber-400 tracking-wider">
            Indicadores de Aprendizagem & Proficiência
          </h2>
          <p class="text-xs text-slate-400">Acompanhamento contínuo dos índices educacionais</p>
        </div>

        <div class="grid grid-cols-1 md:grid-cols-3 gap-6">
          <div
            v-for="kpi in indicators.slice(0, 3)"
            :key="kpi.indicatorId"
            class="bg-slate-900/90 border border-slate-800 rounded-2xl p-6 flex flex-col justify-between shadow-2xl"
          >
            <div>
              <span class="text-xs font-bold text-slate-400 uppercase tracking-wider">{{ kpi.subtitle }}</span>
              <h3 class="text-lg font-black text-slate-100 mt-1">{{ kpi.name }}</h3>
            </div>

            <div class="my-6 text-center">
              <span class="text-5xl font-black text-amber-300">{{ kpi.currentValue }}</span>
              <span class="text-sm font-semibold text-slate-400 ml-1">{{ kpi.unit }}</span>
            </div>

            <div class="pt-4 border-t border-slate-800 flex justify-between text-xs font-semibold">
              <span class="text-slate-400">Meta: {{ kpi.annualTarget }} {{ kpi.unit }}</span>
              <span class="text-emerald-400">Evolução Positiva</span>
            </div>
          </div>
        </div>
      </div>

      <!-- Slide 2: Critical Alerts -->
      <div v-else-if="activeSlide === 2" class="max-w-5xl mx-auto space-y-6">
        <div class="text-center mb-6">
          <h2 class="text-xl lg:text-2xl font-black uppercase text-rose-400 tracking-wider">
            Central de Alertas e Ações Prioritárias
          </h2>
          <p class="text-xs text-slate-400">Pontos que exigem intervenção imediata das equipes</p>
        </div>

        <div class="space-y-4">
          <div
            v-for="alert in alerts.slice(0, 3)"
            :key="alert.alertId"
            class="p-5 rounded-2xl bg-rose-950/40 border border-rose-500/40 flex items-center justify-between"
          >
            <div>
              <div class="text-sm font-bold text-rose-200">{{ alert.title }}</div>
              <p class="text-xs text-slate-300 mt-1">{{ alert.description }}</p>
              <div class="text-[10px] text-slate-400 mt-2">Unidade: {{ alert.schoolName }}</div>
            </div>
            <span class="px-3 py-1 rounded-full bg-rose-500 text-slate-950 text-xs font-black uppercase shrink-0">
              Urgente
            </span>
          </div>
        </div>
      </div>

    </div>

    <!-- TV Footer Controls -->
    <div class="border-t border-slate-800 pt-4 flex items-center justify-between">
      <div class="flex items-center gap-2">
        <button
          v-for="s in [0, 1, 2]"
          :key="s"
          @click="activeSlide = s"
          class="w-3 h-3 rounded-full transition-all"
          :class="activeSlide === s ? 'bg-amber-400 w-8' : 'bg-slate-700'"
        ></button>
      </div>

      <div class="text-xs text-slate-400 font-medium">
        Modo Apresentação TV • Slide {{ activeSlide + 1 }} de 3
      </div>

      <div class="flex items-center gap-2">
        <button
          @click="prevSlide"
          class="p-2 bg-slate-800 hover:bg-slate-700 rounded-lg text-slate-300"
        >
          <ChevronLeft class="w-5 h-5" />
        </button>
        <button
          @click="nextSlide"
          class="p-2 bg-slate-800 hover:bg-slate-700 rounded-lg text-slate-300"
        >
          <ChevronRight class="w-5 h-5" />
        </button>
      </div>
    </div>

    <!-- Institutional Wood Plaque Footer -->
    <div class="mt-4 -mx-6 -mb-6">
      <InstitutionalWoodPlaque />
    </div>

  </div>
</template>

<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue';
import { GraduationCap, X, ChevronLeft, ChevronRight } from 'lucide-vue-next';
import { useCockpit } from '../composables/useCockpit';
import InstitutionalWoodPlaque from './InstitutionalWoodPlaque.vue';

const { isTvMode, mainGoal, indicators, alerts } = useCockpit();

const activeSlide = ref(0);
const currentTime = ref(new Date().toLocaleTimeString('pt-BR'));
let timeInterval: any = null;
let slideInterval: any = null;

const nextSlide = () => {
  activeSlide.value = (activeSlide.value + 1) % 3;
};

const prevSlide = () => {
  activeSlide.value = (activeSlide.value - 1 + 3) % 3;
};

onMounted(() => {
  timeInterval = setInterval(() => {
    currentTime.value = new Date().toLocaleTimeString('pt-BR');
  }, 1000);

  slideInterval = setInterval(() => {
    nextSlide();
  }, 10000);
});

onUnmounted(() => {
  if (timeInterval) clearInterval(timeInterval);
  if (slideInterval) clearInterval(slideInterval);
});
</script>

// src/components/TvPresentationMode.tsx
import React, { useState, useEffect } from 'react';
import {
  Tv,
  X,
  Play,
  Pause,
  ChevronLeft,
  ChevronRight,
  GraduationCap,
  Clock,
  Sparkles,
  School,
  AlertTriangle,
  TrendingUp,
  CheckCircle2,
  Users
} from 'lucide-react';
import { useCockpit } from '../context/CockpitContext';
import { InstitutionalWoodPlaque } from './InstitutionalWoodPlaque';

export const TvPresentationMode: React.FC = () => {
  const { kpis, schools, alerts, highlights, setIsTvMode, userProfile } = useCockpit();

  const [activeSlide, setActiveSlide] = useState<number>(0);
  const [isPlaying, setIsPlaying] = useState<boolean>(true);
  const [currentTime, setCurrentTime] = useState<string>('');
  const [currentDate, setCurrentDate] = useState<string>('');

  const totalSlides = 3;

  // Auto slide cycle every 12 seconds
  useEffect(() => {
    let timer: NodeJS.Timeout;
    if (isPlaying) {
      timer = setInterval(() => {
        setActiveSlide((prev) => (prev + 1) % totalSlides);
      }, 12000);
    }
    return () => clearInterval(timer);
  }, [isPlaying]);

  // Live clock
  useEffect(() => {
    const updateTime = () => {
      const now = new Date();
      setCurrentTime(
        now.toLocaleTimeString('pt-BR', { hour: '2-digit', minute: '2-digit', second: '2-digit' })
      );
      setCurrentDate(
        now.toLocaleDateString('pt-BR', { day: '2-digit', month: '2-digit', year: 'numeric' })
      );
    };
    updateTime();
    const interval = setInterval(updateTime, 1000);
    return () => clearInterval(interval);
  }, []);

  const criticalSchools = schools.filter((s) => s.status === 'critico');
  const topSchools = schools.filter((s) => s.status === 'destaque');

  return (
    <div className="fixed inset-0 z-50 bg-[#060b19] text-white flex flex-col justify-between p-6 overflow-hidden select-none animate-fade-in">
      {/* TV Header Bar */}
      <div className="flex items-center justify-between border-b border-slate-800/80 pb-4">
        <div className="flex items-center gap-4">
          <div className="p-3 bg-gradient-to-br from-amber-500 to-yellow-600 rounded-2xl shadow-xl text-slate-950">
            <GraduationCap className="w-8 h-8" />
          </div>
          <div>
            <div className="flex items-center gap-3">
              <h1 className="text-xl md:text-2xl font-black uppercase tracking-wider bg-gradient-to-r from-amber-200 via-white to-amber-100 bg-clip-text text-transparent">
                PAINEL EXECUTIVO DE INTELIGÊNCIA EDUCACIONAL
              </h1>
              <span className="px-3 py-1 bg-amber-500/20 text-amber-300 font-bold text-xs rounded-full border border-amber-500/40 uppercase">
                {userProfile.municipality}
              </span>
            </div>
            <p className="text-xs text-slate-400 font-medium">
              Monitor de Gestão em Tempo Real • Secretaria Municipal de Educação
            </p>
          </div>
        </div>

        {/* TV Controls & Live Clock */}
        <div className="flex items-center gap-4">
          <div className="flex items-center gap-3 px-4 py-2 bg-slate-900 border border-slate-800 rounded-xl text-slate-200 font-mono text-sm">
            <span>{currentDate}</span>
            <span className="text-amber-400 font-bold">{currentTime}</span>
          </div>

          <div className="flex items-center gap-1.5 bg-slate-900 p-1 border border-slate-800 rounded-xl">
            <button
              onClick={() => setActiveSlide((prev) => (prev - 1 + totalSlides) % totalSlides)}
              className="p-2 text-slate-400 hover:text-white rounded-lg transition"
            >
              <ChevronLeft className="w-5 h-5" />
            </button>
            <button
              onClick={() => setIsPlaying(!isPlaying)}
              className="p-2 text-amber-400 hover:text-amber-300 rounded-lg transition"
            >
              {isPlaying ? <Pause className="w-5 h-5" /> : <Play className="w-5 h-5" />}
            </button>
            <button
              onClick={() => setActiveSlide((prev) => (prev + 1) % totalSlides)}
              className="p-2 text-slate-400 hover:text-white rounded-lg transition"
            >
              <ChevronRight className="w-5 h-5" />
            </button>
          </div>

          <button
            onClick={() => setIsTvMode(false)}
            className="flex items-center gap-2 px-4 py-2 bg-rose-950/80 hover:bg-rose-900 border border-rose-800 text-rose-200 font-bold text-xs rounded-xl transition"
          >
            <X className="w-4 h-4" />
            <span>Sair da TV</span>
          </button>
        </div>
      </div>

      {/* Slide Content */}
      <div className="my-auto py-4">
        {/* SLIDE 0: VISÃO GERAL DE IMPACTO */}
        {activeSlide === 0 && (
          <div className="space-y-6 animate-fade-in">
            <div className="flex items-center justify-between">
              <span className="text-xs font-bold uppercase tracking-widest text-amber-400 flex items-center gap-2">
                <Sparkles className="w-4 h-4 animate-spin" />
                Painel 01 de 03 — Indicadores de Alto Impacto
              </span>
              <span className="text-xs text-slate-400 font-mono">Rotação Automática Ativa</span>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-4 gap-6">
              {/* Index Card */}
              <div className="bg-gradient-to-br from-[#0c1636] to-[#132252] border border-amber-500/40 rounded-2xl p-6 shadow-2xl flex flex-col justify-between">
                <span className="text-xs font-bold uppercase tracking-widest text-slate-300">
                  ÍNDICE GERAL DA EDUCAÇÃO
                </span>
                <div className="my-4">
                  <div className="text-6xl font-black text-amber-300">72,4</div>
                  <div className="text-xs text-emerald-400 font-bold mt-2">↑ +8.7 pts vs ano anterior</div>
                </div>
                <div className="p-3 bg-slate-900/80 rounded-xl border border-slate-800 text-xs text-slate-300">
                  Objetivo 2027: <strong>80,0 pontos</strong>
                </div>
              </div>

              {/* Attendance */}
              <div className="bg-[#0b132a] border border-slate-800 rounded-2xl p-6 shadow-2xl flex flex-col justify-between">
                <span className="text-xs font-bold uppercase tracking-widest text-slate-300">
                  FREQUÊNCIA MÉDIA DA REDE
                </span>
                <div className="my-4">
                  <div className="text-6xl font-black text-sky-400">91,3%</div>
                  <div className="text-xs text-emerald-400 font-bold mt-2">↑ +4.6 pts vs mês anterior</div>
                </div>
                <div className="p-3 bg-slate-900/80 rounded-xl border border-slate-800 text-xs text-slate-300">
                  Meta Municipal: <strong>95,0%</strong>
                </div>
              </div>

              {/* Approval */}
              <div className="bg-[#0b132a] border border-slate-800 rounded-2xl p-6 shadow-2xl flex flex-col justify-between">
                <span className="text-xs font-bold uppercase tracking-widest text-slate-300">
                  TAXA DE APROVAÇÃO
                </span>
                <div className="my-4">
                  <div className="text-6xl font-black text-emerald-400">87,6%</div>
                  <div className="text-xs text-emerald-400 font-bold mt-2">↑ +3.2 pts vs ano anterior</div>
                </div>
                <div className="p-3 bg-slate-900/80 rounded-xl border border-slate-800 text-xs text-slate-300">
                  Meta Municipal: <strong>94,0%</strong>
                </div>
              </div>

              {/* Students at Risk */}
              <div className="bg-[#0b132a] border border-rose-800/80 rounded-2xl p-6 shadow-2xl flex flex-col justify-between">
                <span className="text-xs font-bold uppercase tracking-widest text-rose-300">
                  ALUNOS EM RISCO
                </span>
                <div className="my-4">
                  <div className="text-6xl font-black text-rose-400">427</div>
                  <div className="text-xs text-rose-300 font-bold mt-2">Necessitam atenção da Busca Ativa</div>
                </div>
                <div className="p-3 bg-rose-950/60 rounded-xl border border-rose-800 text-xs text-rose-200">
                  Ações de acompanhamento em andamento
                </div>
              </div>
            </div>
          </div>
        )}

        {/* SLIDE 1: MAPA MUNICIPAL DE ESCOLAS */}
        {activeSlide === 1 && (
          <div className="space-y-6 animate-fade-in">
            <div className="flex items-center justify-between">
              <span className="text-xs font-bold uppercase tracking-widest text-amber-400 flex items-center gap-2">
                <School className="w-4 h-4" />
                Painel 02 de 03 — Panorama Unidades Escolares (108 Unidades)
              </span>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              {/* Destaques */}
              <div className="bg-[#0b132a] border border-emerald-800/80 rounded-2xl p-6 shadow-2xl space-y-4">
                <h3 className="text-sm font-bold uppercase tracking-wider text-emerald-400 flex items-center gap-2">
                  <CheckCircle2 className="w-5 h-5" />
                  Unidades em Destaque na Rede
                </h3>
                <div className="space-y-3">
                  {topSchools.slice(0, 4).map((s) => (
                    <div key={s.id} className="p-3 bg-slate-900 border border-slate-800 rounded-xl flex items-center justify-between">
                      <div>
                        <p className="font-bold text-sm text-slate-100">{s.name}</p>
                        <span className="text-xs text-slate-400">Diretor: {s.director}</span>
                      </div>
                      <div className="text-right">
                        <span className="text-sm font-extrabold text-emerald-400">IDEB {s.ideb}</span>
                        <p className="text-[10px] text-slate-400">Freq. {s.frequencia}%</p>
                      </div>
                    </div>
                  ))}
                </div>
              </div>

              {/* Atenção Prioritária */}
              <div className="bg-[#0b132a] border border-rose-800/80 rounded-2xl p-6 shadow-2xl space-y-4">
                <h3 className="text-sm font-bold uppercase tracking-wider text-rose-400 flex items-center gap-2">
                  <AlertTriangle className="w-5 h-5" />
                  Unidades em Situação Crítica (Atuação Imediata)
                </h3>
                <div className="space-y-3">
                  {criticalSchools.map((s) => (
                    <div key={s.id} className="p-3 bg-slate-900 border border-slate-800 rounded-xl flex items-center justify-between">
                      <div>
                        <p className="font-bold text-sm text-slate-100">{s.name}</p>
                        <span className="text-xs text-slate-400">{s.alunosEmRisco} alunos em risco de evasão</span>
                      </div>
                      <div className="text-right">
                        <span className="text-sm font-extrabold text-rose-400">IDEB {s.ideb}</span>
                        <p className="text-[10px] text-slate-400">Freq. {s.frequencia}%</p>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </div>
        )}

        {/* SLIDE 2: ALERTAS E AÇÕES */}
        {activeSlide === 2 && (
          <div className="space-y-6 animate-fade-in">
            <div className="flex items-center justify-between">
              <span className="text-xs font-bold uppercase tracking-widest text-amber-400 flex items-center gap-2">
                <AlertTriangle className="w-4 h-4" />
                Painel 03 de 03 — Central de Alertas & Intervenções
              </span>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
              <div className="bg-[#0b132a] border border-slate-800 rounded-2xl p-6 shadow-2xl space-y-3">
                <h3 className="text-sm font-bold uppercase text-amber-300">Alertas Disparados no Dia</h3>
                {alerts.slice(0, 4).map((a) => (
                  <div key={a.id} className="p-3 bg-slate-900 rounded-xl border border-slate-800 text-xs">
                    <p className="font-bold text-slate-200">{a.title}</p>
                    <p className="text-slate-400 mt-1">{a.description}</p>
                  </div>
                ))}
              </div>

              <div className="bg-[#0b132a] border border-slate-800 rounded-2xl p-6 shadow-2xl space-y-3">
                <h3 className="text-sm font-bold uppercase text-emerald-400">Destaques da Semana</h3>
                {highlights.map((h) => (
                  <div key={h.id} className="p-3 bg-slate-900 rounded-xl border border-slate-800 text-xs">
                    <p className="font-bold text-slate-200">{h.title}</p>
                    <p className="text-slate-400 mt-1">{h.description}</p>
                  </div>
                ))}
              </div>
            </div>
          </div>
        )}
      </div>

      {/* Bottom Ticker Marquee Bar */}
      <div className="bg-slate-900/90 border-t border-slate-800 p-3 rounded-xl flex items-center justify-between text-xs font-medium">
        <div className="flex items-center gap-3 overflow-hidden">
          <span className="px-2.5 py-0.5 bg-amber-500 text-slate-950 font-bold rounded uppercase shrink-0 text-[10px]">
            Informativo
          </span>
          <p className="text-amber-200 truncate font-mono">
            "Cada dado é um aluno. Cada indicador é uma oportunidade. Cada ação é um futuro melhor. #EducaçãoQueTransforma"
          </p>
        </div>
        <div className="flex items-center gap-2 shrink-0 text-slate-400 font-mono text-[11px]">
          <span>Painel {activeSlide + 1} / {totalSlides}</span>
        </div>
      </div>

      <div className="mt-2 -mx-6 -mb-6">
        <InstitutionalWoodPlaque />
      </div>
    </div>
  );
};
