// src/App.tsx
import React, { useState } from 'react';
import { CockpitProvider, useCockpit } from './context/CockpitContext';
import { Header } from './components/Header';
import { TopKpiCards } from './components/TopKpiCards';
import { KpiMatrixTable } from './components/KpiMatrixTable';
import { RightSidebarPanels } from './components/RightSidebarPanels';
import { KpiDetailModal } from './components/KpiDetailModal';
import { SchoolDetailView } from './components/SchoolDetailView';
import { SchoolComparisonView } from './components/SchoolComparisonView';
import { ActionPlansView } from './components/ActionPlansView';
import { AlertsCenterView } from './components/AlertsCenterView';
import { ApiIntegrationView } from './components/ApiIntegrationView';
import { RadarRecursosView } from './components/RadarRecursosView';
import { MobileSchoolView } from './components/MobileSchoolView';
import { MunicipalityConfigView } from './components/MunicipalityConfigView';
import { TvPresentationMode } from './components/TvPresentationMode';
import { AuthModal } from './components/AuthModal';
import { Footer } from './components/Footer';
import { InstitutionalWoodPlaque } from './components/InstitutionalWoodPlaque';
import { YoYComparisonChart } from './components/YoYComparisonChart';

function MainCockpitContent() {
  const {
    activeTab,
    isTvMode,
    openKpiDetailModal,
    setOpenKpiDetailModal
  } = useCockpit();

  const [isAuthModalOpen, setIsAuthModalOpen] = useState(false);

  // If in TV presentation mode, render TV view fullscreen
  if (isTvMode) {
    return <TvPresentationMode />;
  }

  return (
    <div className="min-h-screen bg-[#060b19] text-slate-100 flex flex-col justify-between selection:bg-amber-500 selection:text-slate-950 font-sans">
      <div>
        <Header onOpenAuthModal={() => setIsAuthModalOpen(true)} />

        <main className="max-w-[1920px] mx-auto p-3 sm:p-4 md:p-6 space-y-6">
          {/* Main Tab Switcher */}
          {activeTab === 'cockpit' && (
            <div className="space-y-6 animate-fade-in">
              <TopKpiCards />

              {/* YoY Comparison Chart Component */}
              <YoYComparisonChart anoBase={2025} anoVigente={2026} />

              <div className="grid grid-cols-1 xl:grid-cols-12 gap-6 items-start">
                <div className="xl:col-span-9">
                  <KpiMatrixTable />
                </div>
                <div className="xl:col-span-3">
                  <RightSidebarPanels />
                </div>
              </div>
            </div>
          )}

          {activeTab === 'escolas' && (
            <div className="animate-fade-in">
              <SchoolDetailView />
            </div>
          )}

          {activeTab === 'comparativo' && (
            <div className="animate-fade-in">
              <SchoolComparisonView />
            </div>
          )}

          {activeTab === 'planos_acao' && (
            <div className="animate-fade-in">
              <ActionPlansView />
            </div>
          )}

          {activeTab === 'alertas' && (
            <div className="animate-fade-in">
              <AlertsCenterView />
            </div>
          )}

          {activeTab === 'api_integracao' && (
            <div className="animate-fade-in">
              <ApiIntegrationView />
            </div>
          )}

          {activeTab === 'radar_recursos' && (
            <div className="animate-fade-in">
              <RadarRecursosView />
            </div>
          )}

          {activeTab === 'mobile_escola' && (
            <div className="animate-fade-in">
              <MobileSchoolView />
            </div>
          )}

          {activeTab === 'configuracao' && (
            <div className="animate-fade-in">
              <MunicipalityConfigView />
            </div>
          )}
        </main>
      </div>

      <Footer />
      <InstitutionalWoodPlaque />

      {/* KPI Detail Modal */}
      <KpiDetailModal
        kpi={openKpiDetailModal}
        onClose={() => setOpenKpiDetailModal(null)}
      />

      {/* Auth Modal */}
      <AuthModal
        isOpen={isAuthModalOpen}
        onClose={() => setIsAuthModalOpen(false)}
      />
    </div>
  );
}

export default function App() {
  return (
    <CockpitProvider>
      <MainCockpitContent />
    </CockpitProvider>
  );
}

// src/App.vue
<template>
  <div class="min-h-screen bg-[#0b1324] text-slate-100 flex flex-col font-sans antialiased selection:bg-amber-500 selection:text-slate-950">
    <!-- Main Header -->
    <Header />

    <!-- Loading Skeleton -->
    <div v-if="isLoading" class="flex-1 max-w-7xl w-full mx-auto p-4 lg:p-8 flex items-center justify-center">
      <div class="flex flex-col items-center gap-3">
        <div class="w-10 h-10 border-4 border-amber-500/30 border-t-amber-400 rounded-full animate-spin"></div>
        <p class="text-xs text-slate-400 font-semibold uppercase tracking-widest">Carregando dados do servidor PostgreSQL e IndexedDB...</p>
      </div>
    </div>

    <!-- Main Content Area -->
    <main v-else class="flex-1 max-w-7xl w-full mx-auto p-4 lg:p-8 space-y-6">
      <!-- Top Summary KPI Cards -->
      <TopKpiCards />

      <!-- Active View Tab Content -->
      <div v-if="activeTab === 'dashboard'" class="grid grid-cols-1 lg:grid-cols-3 gap-6">
        <div class="lg:col-span-2 space-y-6">
          <KpiMatrixTable />
        </div>
        <div class="space-y-6">
          <RightSidebarPanels />
        </div>
      </div>

      <div v-else-if="activeTab === 'escolas'">
        <SchoolComparisonView />
      </div>

      <div v-else-if="activeTab === 'planos_acao'">
        <ActionPlansView />
      </div>
    </main>

    <!-- Institutional Wood Plaque Footer -->
    <InstitutionalWoodPlaque />

    <!-- Modals & Overlays -->
    <KpiDetailModal v-if="isModalOpen && selectedKpi" :kpi="selectedKpi" @close="closeKpiModal" />
    <TvPresentationMode v-if="isTvMode" />
    <AuthModal />
  </div>
</template>

<script setup lang="ts">
import Header from './components/Header.vue';
import TopKpiCards from './components/TopKpiCards.vue';
import KpiMatrixTable from './components/KpiMatrixTable.vue';
import RightSidebarPanels from './components/RightSidebarPanels.vue';
import SchoolComparisonView from './components/SchoolComparisonView.vue';
import ActionPlansView from './components/ActionPlansView.vue';
import InstitutionalWoodPlaque from './components/InstitutionalWoodPlaque.vue';
import KpiDetailModal from './components/KpiDetailModal.vue';
import TvPresentationMode from './components/TvPresentationMode.vue';
import AuthModal from './components/AuthModal.vue';

import { useCockpit } from './composables/useCockpit';

const {
  activeTab,
  isLoading,
  isModalOpen,
  selectedKpi,
  closeKpiModal,
  isTvMode
} = useCockpit();
</script>
